name: CI devops 2021 EPF
on:
  push:
    branches: master
  pull_request:
jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      - name: Build and test with Maven
        run: mvn -B package --file simple-api/pom.xml
  
