name: CI devops 2021 EPF
on:
#to begin you want to launch this job in main and develop
  push:
    branches: master
  pull_request:
jobs:
  build-and-test-backend:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      - name: Build and test with Maven
        run: mvn -B package --file simple-api/pom.xml
  build-and-push-docker-image:
    needs: build-and-test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3
        
      - name: build image and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./simple-api
          tags: ${{secrets.DOCKERHUB_USERNAME}}/TP2_DevOps:simple-api
          
      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          context: ./database
          tagss: ${{secrets.DOCKERHUB_USERNAME}}/TP2_DevOps:database
          
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          context: ./https
          tagss: ${{secrets.DOCKERHUB_USERNAME}}/TP2_DevOps:httpd
  
